version: '3.1'
services:
    message_broker:
        build: ./app/.
        ports:
            - "8001:8001"
        container_name: message_broker
        networks:
            - message_broker_network
    publisher_service:
        build: ./publisher_service/.
        ports:
            - "8081:8081"
        container_name: publisher_service
        networks:
            - message_broker_network
    message_broker_db:
        image: mongo:latest
        ports:
            - "27017:27017"
        container_name: message_broker_db
        networks:
            - message_broker_network
    message_broker_client:
        build: ./react_client/.
        ports:
            - "8080:8080"
        container_name: message_broker_client
        networks:
            - message_broker_network
networks:
        message_broker_network: